### PR TITLE
Adds Import of UIComponent for Routing

### PR DESCRIPTION
**Pull request by flovogt**
Follow-Up of https://github.com/SAP-samples/ui5-typescript-walkthrough/pull/55

### CODE REVIEW

**Comment by flovogt** [comment]
@petermuessig @akudev should we adjust the JS walkthrough the same way? In JS using the `this.getOwnerComponent()` has the benefit to not import the `sap/ui/core/UIComponent` at all.

**Review by akudev — APPROVED** [review]

**Comment by akudev** [comment]
In JS this is less important, I think. If we are using `this.getOwnerComponent()` with less imports there, that's fine.

**Review by KlattG — APPROVED** [review]
LGTM

**Comment by petermuessig** [comment]
Hmmm, isn't Andreas commenting in the other direction? Using `this.getOwnerComponent()` instead of the `import`? Both is OK for me - finally it must be consistent - but I'm questioning the merge of the change with the comment above...

**Comment by akudev** [comment]
@petermuessig that was regarding the JavaScript version. In TypeScript the variant without typecast (= this change) is definitely better.

**Pull request merged**
